# Reference Links

## Helpful tutorials/inspo
* [Servo Motor PWM tutorial](https://blog.wokwi.com/learn-servo-motor-using-wokwi-logic-analyzer/)
* [IR Proximity Sensor inspo](https://www.instructables.com/How-to-Make-a-Proximity-Sensor/)
* [DFPlayer Mini tutorial](https://www.youtube.com/watch?v=7WiSeQxb1bU)

## Datasheets 
* [DFPlayer Datasheet](https://picaxe.com/docs/spe033.pdf)
* [STM32L432KC Datasheet](https://www.st.com/resource/en/datasheet/stm32l412c8.pdf)
* [iCE40 UltraPlus Family Data Sheet](https://hmc-e155.github.io/assets/doc/FPGA-DS-02008-2-0-iCE40-UltraPlus-Family-Data-Sheet.pdf)

## STL Files
* [Toothless Popcorn Bucket STL](https://www.google.com/url?q=https://thangs.com/designer/serev3d/3d-model/Toothless%2520Popcorn%2520Bucket%2520-%2520Cute%2520Functional%2520Container%2520-%2520No%2520Supports%25203D%2520Print%2520STL%252F3MF%2520-%2520Multicolor-1179986?srsltid%3DAfmBOorELNO1pAViiqwn7SVjYEa0bkFhM3gSQqvCqB2wc0x1aRdmUiSE&sa=D&source=docs&ust=1765095611653341&usg=AOvVaw1BDeelP-9spyfWYTSy1TtJ)



# Acknowledgements

We'd like to thank everyone who made this project possible.

Thank you Prof Spencer for pushing us in this class while always being so supportive and understanding. 

Thank you to Xavier Walter for always making time to come help with any computer and electrical issue we could have. This class would not be possible without you.

Thank you to all the TAs (Neil Chulani, Kavi Dey, Troy Kaufman, and, Vikram Krishna) for helping using with debugging various circuits and pieces of code. In particular, thank you to Kavi for all the help with the Analog-to-Digital Converter (ADC).